### ISSUE TITLE
New Badges #1

### ISSUE THREAD

**Issue by OrbitalCardinal** [Kykal/github-badge-generator#7]
Badges for:

1. Python Libraries
- Pandas
- Numpy
- Matplotlib
- Keras
- Scikit-Learn
- Tensorflow
- Jupyter

2. Technologies:
-  SQL
- MySQL
- PostgreSQL
- Firebase
- Flutter
- Dart
- Julia
- Css
- Scss
- Sass
- Typescript
- Javascript
- Java
- Tex
- Latex
- Linux
- Ubuntu
- Debian
- Next JS

**Comment by Kykal** [comment]
1. Python libraries:
- [x] Pandas
- [x] Numpy
- [ ] Matplotlib*
- [x] Keras
- [x] Scikit-Learn
- [x] Tensorflow
- [x] Jupyter

2. Technologies
- [ ] SQL**
- [x] MySQL
- [x] PostgreSQL
- [x] Firebase
- [x] Flutter
- [x] Dart
- [x] Julia
- [ ] Css**
- [ ] Scss**
- [x] Sass
- [x] TypeScript
- [x] JavaScript
- [x] Java
- [ ] Tex**
- [x] LaTeX
- [x] Linux
- [x] Ubuntu
- [x] Debian
- [x] Next.JS

*No logo available, Python logo used instead
**No logo available
